spring:
  application:
     name: web-service
  sleuth:
     sampler:
       percentage: 1.0
eureka:
  client:
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 3
    symbols:
      it: EMC,ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK
logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
